name: Redeploy API

on:
  push:
    branches:
      - master
    paths:
      - "build/**"
  workflow_dispatch:

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger API redeploy
        run: |
          curl -d '' ${{ secrets.VERCEL_API_REDEPLOY_HOOK }}
        shell: bash
